# -*- coding: utf-8 -*-
__author__ = 'Marco Borges'
__version__ = '0.0.1'

#TODO: check if special characters are working and add remaining countries

COUNTRY_MAP = dict(AF='Afghanistan', AL='Albania', DZ='Algeria', AS='American_Samoa', AD='Andorra', AO='Angola',
                   AI='Anguilla', AQ='Antarctica', AG='Antigua_and_Barbuda', AR='Argentina', AM='Armenia', AW='Aruba',
                   AU='Australia', AT='Austria', AZ='Azerbaijan', BS='Bahamas', BH='Bahrain', BD='Bangladesh',
                   BB='Barbados', BY='Belarus', BE='Belgium', BZ='Belize', BJ='Benin', BM='Bermuda', BT='Bhutan',
                   BO='Bolivia', BA='Bosnia_and_Herzegovina', BW='Botswana', BV='Bouvet_Island', BR='Brazil',
                   IO='British_Indian_Ocean_Territory', BN='Brunei_Darussalam', BG='Bulgaria', BF='Burkina_Faso',
                   BI='Burundi', CV='Cabo_Verde', KH='Cambodia', CM='Cameroon', CA='Canada', KY='Cayman_Islands',
                   CF='Central_African_Republic', TD='Chad', CL='Chile', CN='China', CX='Christmas_Island',
                   CO='Colombia', KM='Comoros', CG='Congo', CK='Cook_Islands', CR='Costa_Rica', HR='Croatia', CU='Cuba',
                   CW='Curaçao', CY='Cyprus', CZ='Czechia', DK='Denmark', DJ='Djibouti', DM='Dominica',
                   DO='Dominican_Republic', EC='Ecuador', EG='Egypt', SV='El_Salvador', GQ='Equatorial_Guinea',
                   ER='Eritrea', EE='Estonia', ET='Ethiopia', FO='Faroe_Islands', FJ='Fiji', FI='Finland', FR='France',
                   GF='French_Guiana', PF='French_Polynesia', TF='French_Southern_Territories', GA='Gabon', GM='Gambia',
                   GE='Georgia', DE='Germany', GH='Ghana', GI='Gibraltar', GR='Greece', GL='Greenland', GD='Grenada',
                   GP='Guadeloupe', GU='Guam', GT='Guatemala', GG='Guernsey', GN='Guinea', GW='Guinea-Bissau',
                   GY='Guyana', HT='Haiti', HM='Heard_Island_and_McDonald_Islands', HN='Honduras', HK='Hong_Kong',
                   HU='Hungary', IS='Iceland', IN='India', ID='Indonesia', IQ='Iraq', IE='Ireland', IM='Isle_of_Man',
                   IL='Israel', IT='Italy', JM='Jamaica', JP='Japan', JE='Jersey', JO='Jordan', KZ='Kazakhstan',
                   KE='Kenya', KI='Kiribati', KW='Kuwait', KG='Kyrgyzstan', LV='Latvia', LB='Lebanon', LS='Lesotho',
                   LR='Liberia', LY='Libya', LI='Liechtenstein', LT='Lithuania', LU='Luxembourg', MO='Macao',
                   MG='Madagascar', MW='Malawi', MY='Malaysia', MV='Maldives', ML='Mali', MT='Malta',
                   MH='Marshall_Islands', MQ='Martinique', MR='Mauritania', MU='Mauritius', YT='Mayotte', MX='Mexico',
                   MD='Moldova', MC='Monaco', MN='Mongolia', ME='Montenegro', MS='Montserrat', MA='Morocco',
                   MZ='Mozambique', MM='Myanmar', NA='Namibia', NR='Nauru', NP='Nepal', NL='Netherlands',
                   NC='New_Caledonia', NZ='New_Zealand', NI='Nicaragua', NE='Niger', NG='Nigeria', NU='Niue',
                   NF='Norfolk_Island', MP='Northern_Mariana_Islands', NO='Norway', OM='Oman', PK='Pakistan',
                   PW='Palau', PA='Panama', PG='Papua_New_Guinea', PY='Paraguay', PE='Peru', PH='Philippines',
                   PN='Pitcairn', PL='Poland', PT='Portugal', PR='Puerto_Rico', QA='Qatar', RO='Romania',
                   RU='Russian_Federation', RW='Rwanda', RE='Réunion', BL='Saint_Barthélemy',
                   KN='Saint_Kitts_and_Nevis', LC='Saint_Lucia', PM='Saint_Pierre_and_Miquelon',
                   VC='Saint_Vincent_and_the_Grenadines', WS='Samoa', SM='San_Marino', ST='Sao_Tome_and_Principe',
                   SA='Saudi_Arabia', SN='Senegal', RS='Serbia', SC='Seychelles', SL='Sierra_Leone', SG='Singapore',
                   SK='Slovakia', SI='Slovenia', SB='Solomon_Islands', SO='Somalia', ZA='South_Africa',
                   GS='South_Georgia_and_the_South_Sandwich_Islands', SS='South_Sudan', ES='Spain', LK='Sri_Lanka',
                   SD='Sudan', SR='Suriname', SJ='Svalbard_and_Jan_Mayen', SZ='Swaziland', SE='Sweden',
                   CH='Switzerland', SY='Syrian_Arab_Republic', TW='Taiwan', TJ='Tajikistan', TZ='Tanzania',
                   TH='Thailand', TL='Timor-Leste', TG='Togo', TK='Tokelau', TO='Tonga', TT='Trinidad_and_Tobago',
                   TN='Tunisia', TR='Turkey', TM='Turkmenistan', TC='Turks_and_Caicos_Islands', TV='Tuvalu',
                   UG='Uganda', UA='Ukraine', AE='United_Arab_Emirates', GB='United_Kingdom', US='United_States',
                   UM='United_States_Minor_Outlying_Islands', UY='Uruguay', UZ='Uzbekistan', VU='Vanuatu',
                   VE='Venezuela', VN='Viet_Nam', WF='Wallis_and_Futuna', EH='Western_Sahara', YE='Yemen', ZM='Zambia',
                   ZW='Zimbabwe', AX='Åland_Islands')