# -*- coding: utf-8 -*-
__author__ = 'marco Borges'
__version__ = '0.0.2'

#TODO: check if special characters are working and add remaining countries

COUNTRY_MAP = dict(AF='afghanistan', AL='albania', DZ='algeria', AS='american_Samoa', AD='andorra', AO='angola',
                   AI='anguilla', AQ='antarctica', AG='antigua_and_Barbuda', AR='argentina', AM='armenia', AW='aruba',
                   AU='australia', AT='austria', AZ='azerbaijan', BS='bahamas', BH='bahrain', BD='bangladesh',
                   BB='barbados', BY='belarus', BE='belgium', BZ='belize', BJ='benin', BM='bermuda', BT='bhutan',
                   BO='bolivia', BA='bosnia_and_Herzegovina', BW='botswana', BV='bouvet_Island', BR='brazil',
                   IO='british_Indian_Ocean_Territory', BN='brunei_Darussalam', BG='bulgaria', BF='burkina_Faso',
                   BI='burundi', CV='cabo_Verde', KH='cambodia', CM='cameroon', CA='canada', KY='cayman_Islands',
                   CF='central_African_Republic', TD='chad', CL='chile', CN='china', CX='christmas_Island',
                   CO='colombia', KM='comoros', CG='congo', CK='cook_Islands', CR='costa_Rica', HR='croatia', CU='cuba',
                   CW='curaçao', CY='cyprus', CZ='czechia', DK='denmark', DJ='djibouti', DM='dominica',
                   DO='dominican_Republic', EC='ecuador', EG='egypt', SV='el_Salvador', GQ='equatorial_Guinea',
                   ER='eritrea', EE='estonia', ET='ethiopia', FO='faroe_Islands', FJ='fiji', FI='finland', FR='france',
                   GF='french_Guiana', PF='french_Polynesia', TF='french_Southern_Territories', GA='gabon', GM='gambia',
                   GE='georgia', DE='germany', GH='ghana', GI='gibraltar', GR='greece', GL='greenland', GD='grenada',
                   GP='guadeloupe', GU='guam', GT='guatemala', GG='guernsey', GN='guinea', GW='guinea-Bissau',
                   GY='guyana', HT='haiti', HM='heard_Island_and_McDonald_Islands', HN='honduras', HK='hong_Kong',
                   HU='hungary', IS='iceland', IN='india', ID='indonesia', IQ='iraq', IE='ireland', IM='isle_of_Man',
                   IL='israel', IT='italy', JM='jamaica', JP='japan', JE='jersey', JO='jordan', KZ='kazakhstan',
                   KE='kenya', KI='kiribati', KW='kuwait', KG='kyrgyzstan', LV='latvia', LB='lebanon', LS='lesotho',
                   LR='liberia', LY='libya', LI='liechtenstein', LT='lithuania', LU='luxembourg', MO='macao',
                   MG='madagascar', MW='malawi', MY='malaysia', MV='maldives', ML='mali', MT='malta',
                   MH='marshall_Islands', MQ='martinique', MR='mauritania', MU='mauritius', YT='mayotte', MX='mexico',
                   MD='moldova', MC='monaco', MN='mongolia', ME='montenegro', MS='montserrat', MA='morocco',
                   MZ='mozambique', MM='myanmar', NA='namibia', NR='nauru', NP='nepal', NL='netherlands',
                   NC='new_Caledonia', NZ='new_Zealand', NI='nicaragua', NE='niger', NG='nigeria', NU='niue',
                   NF='norfolk_Island', MP='northern_Mariana_Islands', NO='norway', OM='oman', PK='pakistan',
                   PW='palau', PA='panama', PG='papua_New_Guinea', PY='paraguay', PE='peru', PH='philippines',
                   PN='pitcairn', PL='poland', PT='portugal', PR='puerto_Rico', QA='qatar', RO='romania',
                   RU='russian_Federation', RW='rwanda', RE='réunion', BL='saint_Barthélemy',
                   KN='saint_Kitts_and_Nevis', LC='saint_Lucia', PM='saint_Pierre_and_Miquelon',
                   VC='saint_Vincent_and_the_Grenadines', WS='samoa', SM='san_Marino', ST='sao_Tome_and_Principe',
                   SA='saudi_Arabia', SN='senegal', RS='serbia', SC='seychelles', SL='sierra_Leone', SG='singapore',
                   SK='slovakia', SI='slovenia', SB='solomon_Islands', SO='somalia', ZA='south_Africa',
                   GS='south_Georgia_and_the_South_Sandwich_Islands', SS='south_Sudan', ES='spain', LK='sri_Lanka',
                   SD='sudan', SR='suriname', SJ='svalbard_and_Jan_Mayen', SZ='swaziland', SE='sweden',
                   CH='switzerland', SY='syrian_Arab_Republic', TW='taiwan', TJ='tajikistan', TZ='tanzania',
                   TH='thailand', TL='timor-Leste', TG='togo', TK='tokelau', TO='tonga', TT='trinidad_and_Tobago',
                   TN='tunisia', TR='turkey', TM='turkmenistan', TC='turks_and_Caicos_Islands', TV='tuvalu',
                   UG='uganda', UA='ukraine', AE='united_Arab_Emirates', GB='united_Kingdom', US='united_States',
                   UM='united_States_Minor_Outlying_Islands', UY='uruguay', UZ='uzbekistan', VU='vanuatu',
                   VE='venezuela', VN='viet_Nam', WF='wallis_and_Futuna', EH='western_Sahara', YE='yemen', ZM='zambia',
                   ZW='zimbabwe', AX='aland_Islands')